# Site settings
title: Дарья Веретельникова
header-img: img/img2.jpg
email: koticky@gmail.com
description: "Тарология и психология"
baseurl: ""
url: "http://innercat.ru/"
twitter_username: koticky
facebook_username:  koticky
skype_username: koticky
instagram_username: koticky

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
